### ISSUE TITLE
[CUDA 11.2] Experiment on RTX 3090 with faiss-gpu 1.6.5

### ISSUE THREAD

**Issue by GaoKangYu** [yxgeee/SpCL#36]
After installing all dependencies according to the README, I have encountered several errors. 

By now most of them have been solved.

If you meet the same error, hope you can find some reference here.

My experiment env-info:
```
GPU : RTX 3090
CUDA : 11.2
Python : 3.8
Pytorch : 1.8.0+cu111
Scikit-learn : 0.24.1
```
## Error 1

When I use **faiss-gpu 1.6.3** under **CUDA 10.2**,  process would be killed sometimes when computing 'jaccard distance'.

```
Abnormal Memory usage : Process was killed when computing 'jaccard distance'.
```

### Solution

- Upgrade **scikit-learn** to 0.20.2+.

- Change **n_jobs=-1** to 2 or 4.

[#184](https://github.com/yxgeee/SpCL/blob/master/examples/spcl_train_uda.py#L184)
```
cluster = DBSCAN(eps=eps, min_samples=4, metric='precomputed', n_jobs=4)
cluster_tight = DBSCAN(eps=eps_tight, min_samples=4, metric='precomputed', n_jobs=4)
cluster_loose = DBSCAN(eps=eps_loose, min_samples=4, metric='precomputed', n_jobs=4)
```

## Error 2

```
Abnormal GPU usage
```
When I use **faiss-gpu 1.6.3** under **CUDA 11.2**, the model training can be processed but encountered **CUDA error** soon. 

That's because faiss-gpu 1.6.3 is not compatible with CUDA 11.2.

### Solution
- Upgrade **faiss-gpu** to 1.6.5 by using:
```
conda install -c conda-forge faiss=1.6.5=py38h60a57df_0_cuda
```
- Then I got traceback : "module 'faiss' has no attribute 'cast_integer_to long ptr'", solving that by:

[#L15](https://github.com/yxgeee/SpCL/blob/master/spcl/utils/faiss_utils.py#L15)

```
#replacing "cast_integer_to_long_ptr" by "cast_integer_to_idx_t_ptr"
def swig_ptr_from_LongTensor(x):
    assert x.is_contiguous()
    assert x.dtype == torch.int64, 'dtype=%s' % x.dtype
    # error
    return faiss.cast_integer_to_idx_t_ptr(
        x.storage().data_ptr() + x.storage_offset() * 8)
```

- ### In a word, thanks for **yxgeee's** great work. 👍

**Comment by carywangwang** [comment]
> 根据README安装所有依赖后，遇到了几个错误。
> 
> 至此，大部分问题都已解决。
> 
> 如果你遇到同样的错误，希望你能在这里找到一些参考。
> 
> 我的实验环境信息：
> 
> ```
> GPU : RTX 3090
> CUDA : 11.2
> Python : 3.8
> Pytorch : 1.8.0+cu111
> Scikit-learn : 0.24.1
> ```
> 
> ## 错误 1
> 当我在**CUDA 10.2**下使用**faiss-gpu 1.6.3 时**，有时会在计算“jaccard 距离”时终止进程。****
> 
> ```
> Abnormal Memory usage : Process was killed when computing 'jaccard distance'.
> ```
> 
> ### 解决方案
> * 将**scikit-learn**升级到 0.20.2+。
> * 将**n_jobs=-1**更改为 2 或 4。
> 
> [第184章](https://github.com/yxgeee/SpCL/blob/master/examples/spcl_train_uda.py#L184)
> 
> ```
> cluster = DBSCAN(eps=eps, min_samples=4, metric='precomputed', n_jobs=4)
> cluster_tight = DBSCAN(eps=eps_tight, min_samples=4, metric='precomputed', n_jobs=4)
> cluster_loose = DBSCAN(eps=eps_loose, min_samples=4, metric='precomputed', n_jobs=4)
> ```
> 
> ## 错误 2
> ```
> Abnormal GPU usage
> ```
> 
> 当我在**CUDA 11.2**下使用**faiss-gpu 1.6.3时**，模型训练可以处理，但很快就遇到了**CUDA错误**。********
> 
> 那是因为 faiss-gpu 1.6.3 与 CUDA 11.2 不兼容。
> 
> ### 解决方案
> * 使用以下**命令将 faiss-gpu**升级到 1.6.5：
> 
> ```
> conda install -c conda-forge faiss=1.6.5=py38h60a57df_0_cuda
> ```
> 
> * 然后我得到了回溯：“模块‘faiss’没有属性‘cast_integer_to long ptr’”，通过以下方式解决：
> 
> [#L15](https://github.com/yxgeee/SpCL/blob/master/spcl/utils/faiss_utils.py#L15)
> 
> ```
> #replacing "cast_integer_to_long_ptr" by "cast_integer_to_idx_t_ptr"
> def swig_ptr_from_LongTensor(x):
>     assert x.is_contiguous()
>     assert x.dtype == torch.int64, 'dtype=%s' % x.dtype
>     # error
>     return faiss.cast_integer_to_idx_t_ptr(
>         x.storage().data_ptr() + x.storage_offset() * 8)
> ```
> 
> * ### 总之，感谢**yxgeee 的**出色工作。👍

> 根据README安装所有依赖后，遇到了几个错误。
> 
> 至此，大部分问题都已解决。
> 
> 如果你遇到同样的错误，希望你能在这里找到一些参考。
> 
> 我的实验环境信息：
> 
> ```
> GPU : RTX 3090
> CUDA : 11.2
> Python : 3.8
> Pytorch : 1.8.0+cu111
> Scikit-learn : 0.24.1
> ```
> 
> ## 错误 1
> 当我在**CUDA 10.2**下使用**faiss-gpu 1.6.3 时**，有时会在计算“jaccard 距离”时终止进程。****
> 
> ```
> Abnormal Memory usage : Process was killed when computing 'jaccard distance'.
> ```
> 
> ### 解决方案
> * 将**scikit-learn**升级到 0.20.2+。
> * 将**n_jobs=-1**更改为 2 或 4。
> 
> [第184章](https://github.com/yxgeee/SpCL/blob/master/examples/spcl_train_uda.py#L184)
> 
> ```
> cluster = DBSCAN(eps=eps, min_samples=4, metric='precomputed', n_jobs=4)
> cluster_tight = DBSCAN(eps=eps_tight, min_samples=4, metric='precomputed', n_jobs=4)
> cluster_loose = DBSCAN(eps=eps_loose, min_samples=4, metric='precomputed', n_jobs=4)
> ```
> 
> ## 错误 2
> ```
> Abnormal GPU usage
> ```
> 
> 当我在**CUDA 11.2**下使用**faiss-gpu 1.6.3时**，模型训练可以处理，但很快就遇到了**CUDA错误**。********
> 
> 那是因为 faiss-gpu 1.6.3 与 CUDA 11.2 不兼容。
> 
> ### 解决方案
> * 使用以下**命令将 faiss-gpu**升级到 1.6.5：
> 
> ```
> conda install -c conda-forge faiss=1.6.5=py38h60a57df_0_cuda
> ```
> 
> * 然后我得到了回溯：“模块‘faiss’没有属性‘cast_integer_to long ptr’”，通过以下方式解决：
> 
> [#L15](https://github.com/yxgeee/SpCL/blob/master/spcl/utils/faiss_utils.py#L15)
> 
> ```
> #replacing "cast_integer_to_long_ptr" by "cast_integer_to_idx_t_ptr"
> def swig_ptr_from_LongTensor(x):
>     assert x.is_contiguous()
>     assert x.dtype == torch.int64, 'dtype=%s' % x.dtype
>     # error
>     return faiss.cast_integer_to_idx_t_ptr(
>         x.storage().data_ptr() + x.storage_offset() * 8)
> ```
> 
> * ### 总之，感谢**yxgeee 的**出色工作。👍

您好，我按照您的第二个建议用CUDA11.2在3090上进行了操作，但出现了如下问题，您有好的解决方案吗？

Faiss assertion 'err == CUBLAS_STATUS_SUCCESS' failed in void faiss::gpu::runMatrixMult(faiss::gpu::Tensor<float, 2, true>&, bool, faiss::gpu::Tensor<T, 2, true>&, bool, faiss::gpu::Tensor<IndexType, 2, true>&, bool, float, float, cublasHandle_t, cudaStream_t) [with AT = float; BT = float; cublasHandle_t = cublasContext*; cudaStream_t = CUstream_st*] at /__w/faiss-wheels/faiss-wheels/faiss/faiss/gpu/utils/MatrixMult-inl.cuh:162; details: cublas failed (13): (512, 2048) x (12936, 2048)' = (512, 12936)
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 16706) of binary: /home/anaconda3/envs/pytorch/bin/python

**Comment by Emersonzc** [comment]
how many 3090 did you used for train??  1 or 4,thx
